//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by config.rc
//
#define IDC_BTN_485_OK                  3
#define IDC_BTN_ALARM_IN_TIME_OK        3
#define IDC_BTN_ALARMIN_TIME_COPY       4
#define IDC_BTN_ALARM_OUT_DAY_OK        5
#define IDC_BTN_ALARM_OUT_DAY_COPY      6
#define IDC_BTN_ALARM_IN_OK             7
#define IDC_BTN_ALARMIN_OK              7
#define IDC_BTN_ALARM_IN_COPY           8
#define IDC_BTN_ALARMIN_EXIT            9
#define IDC_BTN_ALARM_OUT_COPY          10
#define IDC_BTN_SET_STATE               11
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_CONFIG_DIALOG               102
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_DEVICE_CFG           129
#define IDD_DIALOG_CHAN_CFG             130
#define IDD_DIALOG_SERIAL_CFG           139
#define IDD_DIALOG_ALARM_CFG            141
#define IDD_DIALOG_USER_CFG             143
#define IDD_DIALOG_EXCEPTION_CFG        145
#define IDD_DLG_REMOTE_SHOW_STRING      149
#define IDD_DLG_REMOTE_HIDE_AREA        151
#define IDD_DLG_REMOTE_HIDE_ALARM       152
#define IDD_DLG_REMOTE_RECORD_SCHEDULE  154
#define IDD_DLG_REMOTE_MOTION_DETECT    156
#define IDD_DLG_REOMTE_VILOST           158
#define IDD_DLG_PPP_CFG                 160
#define IDD_DLG_REMOTE_ALARM_IN_HANDLE  162
#define IDD_DLG_REMOTE_ALARM_IN_PTZ_INVOKE 164
#define IDC_TAB_CONFIG_DLG              1000
#define IDC_EDIT_DEVICE_NAME            1000
#define IDC_EDIT_CHAN_NUM               1001
#define IDC_BTN_EXIT                    1001
#define IDC_ALARM_IN_NUM                1002
#define IDC_SPIN_PRESET                 1002
#define IDC_EDIT_HD_NUM                 1003
#define IDC_EDIT_SERIAL                 1004
#define IDC_EDIT_SOFTWARE_VERSION       1005
#define IDC_BTN_PIC_OK                  1005
#define IDC_EDIT_DSP_SOFTWARE_VERSION   1006
#define IDC_BTN_RECORD_OK               1006
#define IDC_CHECK1                      1007
#define IDC_EDIT_HARDWAR_VERSION        1008
#define IDC_EDIT_PANEL_VERSION          1009
#define IDC_COMBO_CYCLE_RECORD          1010
#define IDC_COMBO_NET_FACE              1011
#define IDC_COMBO_DEVICE_TYPE           1012
#define IDC_ALARM_OUT_NUM               1013
#define IDC_EDIT_YKQID                  1014
#define IDC_COMBO4                      1015
#define IDC_COMBO_MAJORSCALE            1015
#define IDC_COMBO5                      1016
#define IDC_COMBO_MINORSCALE            1016
#define IDC_EDIT_DEVICE_IP              1017
#define IDC_EDIT_IP_MASK                1018
#define IDC_EDIT_GATEWAY_IP             1019
#define IDC_EDIT_DNS1                   1020
#define IDC_EDIT16                      1021
#define IDC_EDIT_DNS2                   1021
#define IDC_EDIT_MAC_ADDR               1022
#define IDC_EDIT18                      1023
#define IDC_EDIT_RESOLVER_IP            1023
#define IDC_EDIT_MAIN_PORT              1024
#define IDC_EDIT_HTTP_PORT              1025
#define IDC_CHK_HA_MONITOR_ALARM        1025
#define IDC_EDIT21                      1026
#define IDC_CHK_HA_INVOKE_ALARM_OUT     1026
#define IDC_EDIT_ALARM_HOST_IP          1027
#define IDC_CHK_HA_REPORT_CENTER        1027
#define IDC_EDIT_ALARM_HOST_PORT        1028
#define IDC_EDIT_MTU                    1029
#define IDC_COMBO_MOTION_DAY_COPY       1029
#define IDC_COMBO_MOTION_WEEKDAY        1030
#define IDC_EDIT_DEV_PORT               1032
#define IDC_DEV_IPADDRESS               1033
#define IDC_BTN_PIC_OK1                 1033
#define IDC_BTN_ChanCfg_OK              1033
#define IDC_EDIT_USERNAME               1034
#define IDC_BUTTON_ALARMCFGSETUP        1034
#define IDC_EDIT_PASSWORD               1035
#define IDC_BUTTON_LOGIN                1036
#define IDC_BUTTON_REFRESH              1037
#define IDC_BTN_REMOTE_NET_OK           1038
#define IDC_BUTTON_REBOOT               1039
#define IDC_BUTTON_SETNETCFG            1040
#define IDC_BUTTON_SETDEVICECFG         1042
#define IDC_BUTTON_SHUTDOWN             1044
#define IDC_COMBO_COMPRESSION_TYPE      1074
#define IDC_BTN_CMP_OK                  1075
#define IDC_BTN_PPP_SETUP               1075
#define IDC_BTN_LOCAL_CHAN_OK           1075
#define IDC_BTN_SETUP                   1075
#define IDC_BTN_REMOTE_CHAN_OK          1076
#define IDC_CHK_INVOKE_JPEG_CAPTURE     1089
#define IDC_EDIT_DURATION_TIME          1090
#define IDC_CHK_LOCAL_BACKUP            1095
#define IDC_COMBO_LOCAL_RIGHT_TYPE      1097
#define IDC_COMBO_PRECISIOIN            1097
#define IDC_COMBO_NET_RIGHT_TYPE        1098
#define IDC_EDIT_CHANNEL_NAME           1106
#define IDC_EDIT_REC_DELAY              1107
#define IDC_COMBO_REC_DELAY             1107
#define IDC_EDIT_PRERECORD_TIME         1108
#define IDC_COMBO_PRERECORD_TIME        1108
#define IDC_COMBO_HOUR_TYPE             1109
#define IDC_COMBO_HIDE_ALARM_SENSITIVE  1111
#define IDC_COMBO_232_STOP_BIT          1113
#define IDC_COMBO_232_CHECK_BIT         1114
#define IDC_COMBO_232_FLOW              1115
#define IDC_COMBO_232_OPERATE_MODE      1116
#define IDC_COMBO_485_STOP_BIT          1117
#define IDC_COMBO_485_CHECK_BIT         1118
#define IDC_COMBO_485_FLOW              1119
#define IDC_COMBO_DECODE_TYPE           1120
#define IDC_SUB_EDIT_DEVICE_NAME        1121
#define IDC_TREE_ALARM_OUT              1121
#define IDC_SUB_EDIT_CHAN_NUM           1122
#define IDC_TREE_REMOTE_CHAN            1122
#define IDC_TREE_CHAN                   1122
#define IDC_SUB_EDIT_YKQID              1123
#define IDC_TREE_LOCAL_CHAN             1123
#define IDC_SUB_EDIT_DEVIP              1124
#define IDC_EDIT_MIN22                  1124
#define IDC_CHK_REDUNDANCY_REC          1125
#define IDC_SUB_EDIT_PORT               1125
#define IDC_CHK_AUDIO_REC               1126
#define IDC_SUB_EDIT_IPMASK             1126
#define IDC_EDIT_IPMASK                 1126
#define IDC_SUB_COMBO_NET_FACE          1127
#define IDC_SUB_EDIT_MACIP              1128
#define IDC_EDIT_MIN41                  1128
#define IDC_SUB_EDIT_RESOLVER_IP        1129
#define IDC_SUB_EDIT_MULTIIP            1130
#define IDC_SUB_EDIT_GATEWAY            1131
#define IDC_SUB_EDIT_HTTP_PORT          1132
#define IDC_SUB_EDIT_DNS_IP1            1133
#define IDC_CHK_DHCP                    1134
#define IDC_EDIT_MIN71                  1137
#define IDC_EDIT_ALARMIN_IP             1138
#define IDC_EDIT_ALARMIN_CHAN           1139
#define IDC_SUB_ALARM_HOSTIP            1140
#define IDC_EDIT_ALARMOUT_IP            1140
#define IDC_SUB_ALARM_HOST_PORT         1141
#define IDC_EDIT_HOUR82                 1141
#define IDC_SUB_MTU                     1142
#define IDC_EDIT_ALARMOUT_CHAN          1142
#define IDC_SUB_DNS_IP2                 1143
#define IDC_STATIC_ALARM_IN_IP          1143
#define IDC_STATIC_ALARM_OUT_IP         1144
#define IDC_COMBO_CHAN                  1145
#define IDC_SUB_EDIT_SERIAL             1145
#define IDC_STATIC_ALARMIN_CHAN         1145
#define IDC_COMBO_RESOLUTION            1146
#define IDC_SUB_HARDWARE_VERSION        1146
#define IDC_STATIC_ALARMOUT_CHAN        1146
#define IDC_COMBO_FRAME_RATE            1147
#define IDC_SUB_SOFTWARE_VERSION        1147
#define IDC_EDIT_ALARMOUT_NAME          1147
#define IDC_COMBO_IMAGE_QUALITY         1148
#define IDC_SUB_QMB_VERSION             1148
#define IDC_COMBO_STREAM_TYPE           1149
#define IDC_SUB_ALARM_IN_NUM            1149
#define IDC_COMBO_BIT_RATE_TYPE         1150
#define IDC_SUB_DSP_VERSION             1150
#define IDC_COMBO_MAX_BIT_RATE          1151
#define IDC_SUB_ALARM_OUT_NUM           1151
#define IDC_CHK_OSD                     1152
#define IDC_SUB_EDIT_HD_NUM             1152
#define IDC_CHK_VILOST                  1153
#define IDC_SUB_CYCLE_RECORD            1153
#define IDC_CHK_RECORD                  1154
#define IDC_SUB_DEVICE_TYPE             1154
#define IDC_BTN_REMOTE_RECORD_SETUP     1155
#define IDC_BTN_MOTION_SETUP            1156
#define IDC_COMBO_HA_WEEKDAY            1156
#define IDC_COMBO_WEEK_DAY              1156
#define IDC_COMBO_VILOST_WEEKDAY        1156
#define IDC_COMBO_ALARMIN_WEEKDAY       1156
#define IDC_CHK_CHAN_NAME               1157
#define IDC_STATIC_MAJOR                1157
#define IDC_COMBO_ALARM_OUT_COPY_DAY    1157
#define IDC_COMBO_HIDE_ALARM_DAY_COPY   1157
#define IDC_CHK_ALL_DAY                 1157
#define IDC_COMBO_VILOST_COPY_DAY       1157
#define IDC_COMBO_ALARMIN_COPY_TIME     1157
#define IDC_CHK_HIDE_AREA               1158
#define IDC_STATIC_MINOR                1158
#define IDC_COMBO_ALARM_OUT_WEEKDAY     1158
#define IDC_COMBO_ALL_DAY_TYPE          1158
#define IDC_BTN_HIDE_SETUP              1159
#define IDC_COMBO_TIME_REC_TYPE1        1159
#define IDC_CHK_DISPLAY_WEEK            1160
#define IDC_COMBO_TIME_REC_TYPE5        1160
#define IDC_CHK_MOTION                  1161
#define IDC_BTN_HIDE_ALARM_SETUP        1162
#define IDC_COMBO_TIME_REC_TYPE2        1162
#define IDC_CHK_HIDE_ALARM              1163
#define IDC_EDIT_HOUR31                 1163
#define IDC_BTN_VILOST_SETUP            1164
#define IDC_STATIC_DECODER              1164
#define IDC_COMBO_TIME_REC_TYPE3        1164
#define IDC_COMBO_VIDEO_TYPE            1165
#define IDC_STATIC_DECODER_ADDR         1165
#define IDC_EDIT_HOUR41                 1165
#define IDC_COMBO_AUDIO_TYPE            1166
#define IDC_COMBO_TIME_REC_TYPE4        1166
#define IDC_COMBO_COPY_WEEKDAY          1167
#define IDC_COMBO_COPY_ALARM_IN         1168
#define IDC_BTN_REMOTE_REC_COPY         1168
#define IDC_COMBO_COPY_CHAN             1169
#define IDC_COMBO_COPY_ALARM_OUT        1169
#define IDC_BTN_CHAN_COPY               1170
#define IDC_COMBO_232_BAUD              1171
#define IDC_COMBO_232_DATA_BIT          1172
#define IDC_COMBO_485_CHANNEL           1173
#define IDC_COMBO_485_BAUD              1174
#define IDC_COMBO_485_DATA_BIT          1175
#define IDC_COMBO_TIME_REC_TYPE6        1175
#define IDC_EDIT_DECODE_ADDRESS         1176
#define IDC_COMBO_TIME_REC_TYPE7        1176
#define IDC_COMBO_485_COPY_CFG          1177
#define IDC_COMBO_TIME_REC_TYPE8        1177
#define IDC_BTN_485_COPY                1178
#define IDC_SPIN_CRUISE                 1178
#define IDC_COMBO_ALARM_IN              1179
#define IDC_COMBO_PPP_MODE              1179
#define IDC_SPIN_TRACK                  1179
#define IDC_COMBO_232_CHANNEL           1180
#define IDC_COMBO_ALARM_IN_TYPE         1180
#define IDC_COMBO_REDIAL_MODE           1180
#define IDC_COMBO_ALARM_OUT             1181
#define IDC_CHK_EXCEPTION_MONITOR_ALARM 1182
#define IDC_CHK_MONITOR_ALARM           1182
#define IDC_CHK_VILOST_MONITOR_ALARM    1182
#define IDC_CHK_ALARMIN_MONITOR         1182
#define IDC_CHK_EXCEPTION_AUDIO_ALARM   1183
#define IDC_CHK_HA_AUDIO_ALARM          1183
#define IDC_CHK_AUDIO_ALARM             1183
#define IDC_CHK_VILOST_AUDIO_ALARM      1183
#define IDC_CHK_ALARMIN_VOICE           1183
#define IDC_CHK_EXCEPTION_REPORT_CENTER 1184
#define IDC_CHK_REPORT_CENTER           1184
#define IDC_CHK_VILOST_REPORT_CENTER    1184
#define IDC_CHK_ALARMIN_UPLOAD_CENTER   1184
#define IDC_CHK_EXCEPTION_INVOKE_ALARM_OUT 1185
#define IDC_CHK_INVOKE_ALARM_OUT        1185
#define IDC_CHK_VILOST_INVOKE_ALARM_OUT 1185
#define IDC_CHK_ALARMIN_INVOKE_ALARMOUT 1185
#define IDC_EDIT_HOUR51                 1186
#define IDC_RADIO_PRESET                1186
#define IDC_RADIO_CRUISE                1187
#define IDC_RADIO_TRACK                 1188
#define IDC_EDIT_HOUR11                 1189
#define IDC_COMBO_USER_SEL              1189
#define IDC_EDIT_USER_NAME              1190
#define IDC_EDIT_USER_IP                1191
#define IDC_EDIT_USER_PWD               1192
#define IDC_EDIT_USER_VERIFY_PWD        1193
#define IDC_CHK_LOCAL_PTZ_CTRL          1194
#define IDC_CHK_LOCAL_REC_MANUAL        1195
#define IDC_CHK_MOTION_DETECT_SHOW      1195
#define IDC_CHK_LOCAL_PLAY_BACK         1196
#define IDC_CHK_MOTION_DETECT_SET       1196
#define IDC_CHK_LOCAL_SHOW_STAT         1197
#define IDC_COMBO_MOTION_SENSITIVE      1197
#define IDC_CHK_LOCAL_HIGH_OPERATION    1198
#define IDC_CHK_NET_PREVIEW             1200
#define IDC_CHK_REMOTE_ALARM            1201
#define IDC_CHK_REMOTE_CTRL_LOCAL_OUT   1202
#define IDC_CHK_REOMTE_SERIAL_CTRL      1203
#define IDC_CHK_NET_IP_ACCESS           1204
#define IDC_EDIT_USER_MAC_ADDR1         1205
#define IDC_CHK_LOCAL_SET_PARAM         1206
#define IDC_CHK_REMOTE_PTZ_CTRL         1207
#define IDC_CHK_REMOTE_REC_MANUAL       1208
#define IDC_CHK_REMOTE_PLAY_BACK        1209
#define IDC_CHK_REMOTE_SHOW_STAT        1210
#define IDC_CHK_REMOTE_HIGH_OPERATION   1211
#define IDC_CHK_VOICE_TALK              1212
#define IDC_CHK_REMOTE_SET_PARAM        1213
#define IDC_EDIT_USER_MAC_ADDR2         1214
#define IDC_EDIT_USER_MAC_ADDR3         1215
#define IDC_EDIT_USER_MAC_ADDR4         1216
#define IDC_EDIT_USER_MAC_ADDR5         1217
#define IDC_EDIT_USER_MAC_ADDR6         1218
#define IDC_CHK_LOCAL_REBOOT            1219
#define IDC_CHK_LOCAL_IP_ACCESS         1221
#define IDC_CHK_NET_REBOOT              1222
#define IDC_COMBO_PRIORITY              1223
#define IDC_PIC_DETECT_AREA             1235
#define IDC_PIC_HIDE_ALARM              1235
#define IDC_PIC_MOTION_DETECT           1235
#define IDC_EDIT_CHAN_NAME_X            1307
#define IDC_EDIT_CHAN_NAME_Y            1308
#define IDC_EDIT_OSD_X                  1312
#define IDC_EDIT_OSD_Y                  1313
#define IDC_COMBO_OUT_DELAY             1313
#define IDC_COMBO_OSD_ATTRIB            1314
#define IDC_COMBO_OSD_TYPE              1315
#define IDC_CHK_ALARM_IN_HANDLE         1324
#define IDC_BTN_ALARM_IN_HANDLE         1325
#define IDC_BTN_ALARM_IN_PTZ            1326
#define IDC_COMBO_PTZ_LINKAGE__CHAN     1326
#define IDC_EDIT_PRESET_NO              1330
#define IDC_EDIT_CRUISE_NO              1331
#define IDC_EDIT_TRACK_NO               1332
#define IDC_EDIT_PWD                    1333
#define IDC_EDIT_VERIFY_PWD             1334
#define IDC_CHK_HIDE_AREA_SHOW          1340
#define IDC_CHK_HIDE_AREA_SET           1341
#define IDC_EDIT_ALARM_IN_NAME          1342
#define ID_BTN_HIDE_AREA_EXIT           1346
#define ID_BTN_HIDE_ALARM_EXIT          1346
#define ID_BTN_REMOTE_REC_EXIT          1346
#define ID_BTN_MOTION_EXIT              1346
#define ID_BTN_PTZ_EXIT                 1346
#define ID_BTN_CHAN_CFG_OK              1363
#define IDC_BTN_ALARM_OUT_OK            1365
#define ID_BTN_MOTION_OK                1366
#define ID_BTN_HIDE_AREA_OK             1367
#define ID_BTN_PTZ_OK                   1368
#define ID_BTN_REMOTE_REC_OK            1369
#define ID_BTN_SERIAL_232_OK            1370
#define ID_BTN_USER_OK                  1372
#define IDC_EDIT_REMOTEIP               1433
#define IDC_EDIT_LOCALIP                1434
#define IDC_CHK_REDIAL                  1435
#define IDC_EDIT_TEL_NUM                1436
#define IDC_CHK_DATA_ENCRYPT            1437
#define ID_BTN_HIDE_ALARM_OK            1451
#define IDC_CHK_HIDE_ALARM_SHOW         1452
#define IDC_BTN_EXCEPTION_OK            1453
#define IDC_BTN_STRING_OK               1453
#define IDC_CHK_HIDE_ALARM_SET          1453
#define IDC_BTN_STRING_EXIT             1454
#define IDC_BTN_STRING_SET              1455
#define IDC_BTN_TRANSPARENT_TRANSPORT   1462
#define IDC_EDIT_BIT_RATE               1466
#define IDC_BTN_HIDE_ALARM_DAY_OK       1486
#define IDC_BTN_HA_DAY_COPY             1487
#define IDC_MOTION_DAY_OK               1488
#define IDC_BTN_MOTION_DAY_COPY         1489
#define IDC_BTN_VILOST_DAY_OK           1490
#define IDC_BTN_VILOST_DAY_COPY         1491
#define IDC_BTN_VILOST_OK               1492
#define IDC_BTN_VILOST_EXIT             1493
#define IDC_COMBO_EXCEPTION_TYPE        1495
#define IDC_BTN_STRING                  1497
#define IDC_EDIT_FRAME_I_INTERVAL       1512
#define IDC_COMBO_FRAME_BP_INTERVAL     1514
#define IDC_SUB_COMBO_USE_ZOOM          1516
#define IDC_SUB_COMBO_MINOR_ZOOM        1517
#define IDC_CHK_SHOW                    1524
#define IDC_COMBO_SHOW_AREA             1525
#define IDC_EDIT_STRING                 1526
#define IDC_EDIT_STRING_X               1527
#define IDC_EDIT_STRING_Y               1528
#define IDC_STATICSCALE                 1585
#define IDC_EDIT_HOUR12                 2110
#define IDC_EDIT_MIN11                  2119
#define IDC_EDIT_MIN12                  2121
#define IDC_EDIT_MIN21                  2122
#define IDC_EDIT_HOUR22                 2123
#define IDC_EDIT_MIN31                  2125
#define IDC_EDIT_HOUR32                 2126
#define IDC_EDIT_MIN32                  2127
#define IDC_EDIT_HOUR42                 2129
#define IDC_EDIT_MIN42                  2130
#define IDC_EDIT_MIN51                  2131
#define IDC_EDIT_HOUR52                 2132
#define IDC_EDIT_MIN52                  2133
#define IDC_EDIT_MIN61                  2134
#define IDC_EDIT_HOUR62                 2135
#define IDC_EDIT_MIN62                  2136
#define IDC_EDIT_HOUR72                 2138
#define IDC_EDIT_MIN72                  2139
#define IDC_EDIT_MIN81                  2140
#define IDC_EDIT_STATE                  2141
#define IDC_EDIT_MIN82                  2142
#define IDC_EDIT_HOUR21                 2163
#define IDC_EDIT_HOUR71                 2168
#define IDC_EDIT_HOUR81                 2169
#define IDC_EDIT_HOUR61                 2176

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        165
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1038
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
