//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by PlayBack.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_PLAYBACK_DIALOG             102
#define IDR_MAINFRAME                   128
#define IDD_PAGE_REMOTE                 129
#define IDI_FASTBACKWARD_DISABLE        130
#define IDD_PAGE_LOCAL                  131
#define IDI_FASTBACKWARD_ENABLE         131
#define IDI_FASTFORWARD_DISABLE         132
#define IDD_DIALOG_ADD_DEV              133
#define IDD_PAGE_TIME                   134
#define IDI_FASTFORWARD_ENABLE          134
#define IDI_GOTOEND_DISABLE             135
#define IDI_GOTOEND_ENABLE              136
#define IDI_GOTOSTART_DISABLE           137
#define IDI_GOTOSTART_ENABLE            138
#define IDI_PAUSE_DISABLE               139
#define IDI_PAUSE_ENABLE                140
#define IDI_PLAY_DISABLE                141
#define IDI_PLAY_ENABLE                 142
#define IDI_SOUND_DISABLE               143
#define IDI_SOUND_ENABLE                144
#define IDI_STOP_DISABLE                145
#define IDI_STOP_ENABLE                 146
#define IDI_PIC                         201
#define IDI_STEP_ENABLE                 202
#define IDI_STEP_DISABLE                203
#define IDI_STEPBACK_ENABLE             204
#define IDI_STEPBACK_DISABLE            205
#define IDC_TREE_DEVICE                 1000
#define IDC_TREE_CHAN                   1001
#define IDC_COMBO_TYPE                  1003
#define IDC_STATIC_PORT                 1004
#define IDC_DATE_START                  1005
#define IDC_DATE_END                    1006
#define IDC_STATIC_USER                 1007
#define IDC_EDIT_USER                   1008
#define IDC_STATIC_PWD                  1009
#define IDC_EDIT_PWD                    1010
#define IDC_TIME_START                  1012
#define IDC_STATIC_NODE                 1012
#define IDC_TIME_END                    1013
#define IDC_EDIT_NODE                   1013
#define IDC_BUTTON_LOGIN                1013
#define IDC_STATIC_DEV_IP               1014
#define IDC_IPADDRESS_DEV               1015
#define IDC_FILE_LIST                   1016
#define IDC_EDIT_PORT                   1016
#define IDC_COMBO_FILE_PROPERTY         1017
#define IDC_STATIC_PLAY                 1018
#define IDC_BUTTON_SEARCH               1019
#define IDC_BUTTON_UNLOCK               1020
#define IDC_BUTTON_DOWNLOAD             1021
#define IDC_PROGRESS_DOWNLOAD           1022
#define IDC_BUTTON_PLAY                 1023
#define IDC_BUTTON_REMOTE_PLAY          1023
#define IDC_SLIDER_PLAY                 1024
#define IDC_COMBO_TYPE_LOCAL            1025
#define IDC_BUTTON_STOP                 1025
#define IDC_BUTTON_REMOTE_STOP          1025
#define IDC_DATE_START_LOCAL            1026
#define IDC_BUTTON_SLOW                 1026
#define IDC_BUTTON_SLOW_BYTIME          1026
#define IDC_TIME_START_LOCAL            1027
#define IDC_BUTTON_FAST                 1027
#define IDC_BUTTON_FAST_BYTIME          1027
#define IDC_DATE_END_LOCAL              1028
#define IDC_TIME_END_LOCAL              1029
#define IDC_BUTTON_BACK                 1029
#define IDC_BUTTON_REMOTE_BACK          1029
#define IDC_BUTTON_SEARCH_LOCAL         1030
#define IDC_BUTTON_STEP                 1030
#define IDC_BUTTON_REMOTE_STEP          1030
#define IDC_BUTTON_DEL                  1031
#define IDC_BUTTON_DEL_ALL              1032
#define IDC_BUTTON_PLAY_LOCAL           1033
#define IDC_SLIDER_PLAY_LOCAL           1034
#define IDC_PROGRESS_PLAY_LOCAL         1035
#define IDC_EDIT_FILE_INFO              1036
#define IDC_BUTTON_STOP_LOCAL           1036
#define IDC_BUTTON_FAST_LOCAL           1037
#define IDC_TAB_PLAYBACK                1038
#define IDC_BUTTON_SLOW_LOCAL           1038
#define IDC_STATIC_SEARCH               1039
#define IDC_BUTTON_STEP_LOCAL           1039
#define IDC_STATIC_FRAME                1041
#define IDC_DATE_START_TIME             1042
#define IDC_TIME_START_TIME             1043
#define IDC_DATE_END_TIME               1044
#define IDC_TIME_END_TIME               1045
#define IDC_STATIC_PLAY_WND_TIME        1046
#define IDC_SLIDER_PLAY_TIME            1047
#define IDC_BUTTON1                     1054
#define IDC_BUTTON_STOP_TIME            1054
#define IDC_BUTTON_REMOTE_PIC           1054
#define IDC_BUTTON_STOP_BYTIME          1054
#define IDC_BUTTON2                     1055
#define IDC_BUTTON_SAVE                 1055
#define IDC_BUTTON_REMOTE_SOUND         1055
#define IDC_BUTTON_PLAY_BYTIME          1056
#define IDC_STATIC_PLAY_LOCAL           1060
#define IDC_SLIDER_VOLUME               1062
#define IDC_BUTTON_REMOTE_SLOW          1063
#define IDC_BUTTON_REMOTE_FAST          1064
#define IDC_BUTTON_REMOTE_SAVE          1065
#define IDC_BUTTON_REMOTE_STOP_SAVE     1066

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        135
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1067
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
